### ISSUE TITLE
myTeam Subscription

### ISSUE THREAD

**Issue by MoonTahoe** [eveporcello/graphql-fun#48]
It's time to let the player know they have been grouped into a team. The `myTeam` subscription should return the currentUsers team once teams have been created.

```graphql
type Subscription {
   myTeam: Team
}
```

```graphql
subscription {
    myTeam {
        color
        players {
             name
             avatar
        }
   }
}
```

### Filtering
This code is not exactly correct, but we can use it for reference. `graphql-yoga` came with a `withFilter` function, I am assuming `apollo-server` also has this funciton? You can use it to filter thorugh subscriptions and only reply to the current player or something.

```javascript
export const Subscription = {
     myTeam: {
          subscribe(_, args, { currentPlayer }) {
                  //
                  //  TODO: Obtain the currentPlayer here, can't subscribe to my team unless logged in
                  //

                  return withFilter(
                          (_, { events }, { pubsub }) => pubsub.asyncIterator(events),
                          ({ teams:{event, color} }, { events }, { currentPlayer }) => {
                                 if ((event === 'TEAMS_CREATED') && currentPlayer) {
                                        let theTeam = teams.find(t => t.color === color)
                                        return theTeam && theTeam.players.map(p => p.login).includes(currentPlayer.login)
              }
              return true
            }
        )
          }
     }
}
```

### TODO
* [ ] Setup Playground Test
    * [ ] Authorize a fake user
    * [ ] Add Token to Header
    * [ ] Subscribe to my team
* [ ] Push team information when team has been created
* [ ] Push team information when team has been destroyed
* [ ] Write Tests for this feature
