### ISSUE TITLE
Travis Autodeployments broken

### ISSUE THREAD

**Issue by MoonTahoe** [eveporcello/graphql-fun#91]
It seems like the entire build needs to take less than 60 seconds on heroku, and now webapck is taking longer. I think the solution is to handle the production build on Travis, skip cleanup, and simply start the already built production app on Heroku.

### Tasks
* [ ] Build and Test on Travis
* [ ] If Tests pass, rebuild with production environment vars before deploy
* [ ] Add the Mobile React-Icons back to Connection page
